import type { Metadata } from "next";
import PanelLayout from "@/layouts/panel/PanelLayout";
import { NextIntlClientProvider, Locale, hasLocale } from 'next-intl';
import { ThemeProvider } from "next-themes";
import { ActiveThemeProvider } from "@/components/layouts/themes/active-theme";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";
import { fontVariables } from "@/utils/fonts";
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { Toaster } from "@/components/ui/sonner"
import { META_THEME_COLORS } from "@/utils/constants";
import "@/styles/globals.css"


export const metadata: Metadata = {
  title: "MeKa Next Kit App ~ Login Page",
  description: "Generated by MeKa Next Kit App ~ Login Page",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
};

export default async function RootLayout({ children, params }: Props) {

  const cookieStore = await cookies()
  const activeThemeValue = cookieStore.get("active_theme")?.value
  const isScaled = activeThemeValue?.endsWith("-scaled")

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className="dark" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          activeThemeValue ? `theme-${activeThemeValue}` : "",
          isScaled ? "theme-scaled" : "",
          fontVariables
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ActiveThemeProvider initialTheme={activeThemeValue}>
            <PanelLayout>
              <NextIntlClientProvider>
                {children}
              </NextIntlClientProvider>
            </PanelLayout>
          </ActiveThemeProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}