// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hello world!"
  },
  "auth": {
    "SignIn": {
      "title": "Sign In",
      "form": {
        "email": "Email",
        "password": "Password",
        "submit": "Sign In"
      }
    },
    "SignUp": {
      "title": "Sign Up",
      "form": {
        "name": "Name Surname",
        "email": "Email",
        "password": "Password",
        "passwordConfirm": "Confirm Password",
        "submit": "Sign Up"
      }
    },
    "global": {
      "fillAllFields": "Please fill in all fields."
    }
  }
};
export default messages;